set nocount on;
go

if object_id(N'dbo.sanction_requested', N'U') is null
begin
  create table dbo.[sanction_requested] (
    [id] int identity(1,1) not null,
    [sanctionid] nvarchar(15) null,
    [dte] datetime null,
    [startTime] time(7) null,
    [clubcode] nvarchar(5) null,
    [tournname] nvarchar(100) null,
    [taddr] nvarchar(80) null,
    [tournhost] nvarchar(75) null,
    [site] nvarchar(80) null,
    [number_of_teams] int null,
    [agedivision] nvarchar(50) null,
    [division] nvarchar(20) null,
    [entry_fee] money null,
    [paymentType] varchar(50) null,
    [check_payable_to] nvarchar(50) null,
    [CCPayment] char(1) null default ('N'),
    [paymentURL] nvarchar(100) null,
    [awards] nvarchar(3) null,
    [display_this_record] nvarchar(3) null,
    [pool_play] nvarchar(50) null,
    [otherformat] nvarchar(50) null,
    [playoff_format] nvarchar(50) null,
    [qtr_finals] nvarchar(15) null,
    [semi_finals] nvarchar(15) null,
    [finals] nvarchar(15) null,
    [locker_room] nvarchar(3) null,
    [showers] nvarchar(3) null,
    [food] nvarchar(10) null,
    [closing_dte] datetime null,
    [type] nvarchar(10) null,
    [status] nvarchar(10) null,
    [priority] tinyint null,
    [comments1] nvarchar(200) null,
    [comments2] nvarchar(200) null,
    [HDP] char(1) null default ('N'),
    [season] char(4) null,
    [instructions] text null,
    [TournamentContact_address] nchar(200) null,
    [TournamentDirector_Name] nchar(75) not null,
    [TournamentDirector_Email] nchar(75) null,
    [TournamentDirector_homePhone] nchar(20) null,
    [TournamentDirector_TournamentPhone] nchar(20) null,
    [Expense_facility] decimal(10,2) null default ((0)),
    [Expense_sanctionFees] decimal(10,2) null default ((0)),
    [Expense_officialsFees] decimal(10,2) null default ((0)),
    [Expense_volleyballs] decimal(10,2) null default ((0)),
    [Expense_awards] decimal(10,2) null default ((0)),
    [Expense_supplies] decimal(10,2) null default ((0)),
    [Expense_other] decimal(10,2) null default ((0)),
    [Expense_totals] decimal(10,2) null default ((0)),
    [fee] decimal(10,2) null default ((0)),
    [teams] int null default ((0)),
    [totalbox] decimal(10,2) null default ((0)),
    [otherIncome] decimal(10,2) null default ((0)),
    [netIncome] decimal(10,2) null default ((0)),
    [TournamentContact_name] nchar(80) null,
    [information] text null,
    [SAGO] varchar(1) null default ('N'),
    [sanctionStatus] varchar(12) null default ('Pending'),
    [feeincrease] char(1) null default ('N'),
    [requester] nvarchar(100) null,
    [sanctionNotes] text null,
    [submitDate] smalldatetime null default (getdate()),
    [updated] datetime null default (getdate()),
    [posted] char(1) not null default ('N'),
    [AES_closedDate] datetime null,
    [AES_scoresheets] datetime null,
    [AES_added] datetime null,
    [AES_okToPay] char(1) null,
    [AES_notes] text null,
    [min_number_of_teams] int null,
    [alternateFee] decimal(10,2) null default ((0)),
    constraint [PK_sanction_requested] primary key ([id])
  );
  print 'created dbo.sanction_requested';
end
else
  print 'exists dbo.sanction_requested';
go
